baseurl = "/"
languageCode = "en-us"
title = "Factory 620 LLC"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Factory 620 LLC"
	description = "Software for your Buiness"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Factory 620 LLC"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Your business, powered by Factory 620"
		subtitle   = "Web / mobile / desktop apps to give you a helping hand."
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "Why Factory 620?"
		description = "What good is latest technology if it makes your business needs take a back seat? Factory 620 believes it should be the other way around. A web site, a mobile or desktop app must bring value to you, whether by enhancing what you do best or by making the rough parts of your business smoother. <br/><br/> Want to update your web site yourself to show the answer to common questions from customers? Need a mobile app so that your employees can update inventory from the delivery location? That old spreasheet to stay on top of costs - is it getting a bit long in the tooth? Factory 620 can build a solution to help you run your business better."
		buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "Services"

		[[params.services.list]]
		icon = "fa-html5"
		title = "Web Applications"
		description = "Highly-interactive web applications"

		[[params.services.list]]
		icon = "fa-mobile"
		title = "Mobile Applications"
		description = "For iOS and Android"

		[[params.services.list]]
		icon = "fa-building-o"
		title = "Backend Applications"
		description = "Server-side web applications that support front-end web and mobile applications"

		[[params.services.list]]
		icon = "fa-cogs"
		title = "DevOps Practices"
		description = "Implement and train Continuous Integration and Delievery and automation"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to talk about what Factory 620 can do for you? Call or email us to get started."
		phone = "512-850-4843"
		email = "info@factory620.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
